### ISSUE TITLE
unable to push to GitHub from jupyter-dev

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/storytelling-with-data#135]
I've been getting the "`This version can load notebook formats or earlier.`" error whenever I try to open notebooks on the main jupyterhub server, so I've been using jupyter-dev instead for the last week or so.  I went to push some commits just now and got this error:
```
[f0028ph@polaris-old storytelling-with-data]$ git push
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/paxtonfitzpatrick/storytelling-with-data.git/info/refs

fatal: HTTP request failed
```
Following the link brings you to a page that says 
```
Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
```

This sounds like it might be the problem I'm having, since jupyter-dev also has git version 1.7.1 installed https://ask.cronweekly.com/d/18-github-com-no-longer-supports-git-over-dumb-http

I tried changing the remote URL to ssh (`git@github.com:paxtonfitzpatrick/storytelling-with-data.git`) but that didn't work either and now I'm getting a different error:
```
[f0028ph@polaris-old storytelling-with-data]$ git push
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

Would it be possible to upgrade the version of `git` on jupyter-dev to >=1.7.9?

**Comment by jeremymanning** [comment]
@paxtonfitzpatrick another student also encountered this issue (not sure why it happens).  I solved it by deleting their stored credentials (`git config --global --unset credential.helper`), generating a new token (you're using 2FA, right?), and then re-entering that token as their password.  Then you can store the credentials again using `git config credential.helper store`.

**Comment by jeremymanning** [comment]
migrating to google colab in the next iteration of this course...therefore tagging this with `wontfit`
