### ISSUE TITLE
losing internet connectionn with JupyterHub open in browser locks you out

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/storytelling-with-data#66]
If you disconnect from the internet (e.g., eduroam going down momentarily, changing WiFi networks, letting computer go to sleep) while signed into JupyterHub, the connection to the server is lost, which is expected.

However, if you refresh the page or go to jupyter.dartmouth.edu again, you're automatically redirected to your signed-in account, at `https://jupyter.dartmouth.edu/user/kiewit%5C<NetID>/tree?` and get the error message:
`404: Not Found. You are requesting a page that does not exist.`

From this page, you're unable to sign out and sign back in to reset the connection.

The way I've gotten around this is to open jupyter.dartmouth.edu in an incognito window, sign in there, then refresh my signed-in page.  Is there a better way to do this, or a way to keep it from happening?

**Comment by jeremymanning** [comment]
What's the status of this? Was the issue resolved?

**Comment by jeremymanning** [comment]
Closing this issue, as we could not replicate it
